apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config{{ .Values.upf.config }}
  labels:
    epc-mode: upf{{ .Values.upf.config }}
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log

    upf:
        pfcp:
           dev: {{ .Values.k8s.interface }}
        gtpu:
          - dev: {{ .Values.k8s.interface }}
            advertise: {{ .Values.upf.lbIP }}
        subnet:
          - addr: 10.{{ .Values.upf.tun }}.0.1/16
            dev: {{ .Values.upf.device }}
            dnn: {{ .Values.upf.dnn }}
