apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config{{ .Values.upf.config }}
  labels:
    epc-mode: upf
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log

    upf:
        pfcp:
           dev: {{ .Values.k8s.interface }}
        gtpu:
          - dev: {{ .Values.k8s.interface }}
          # : 10.10.10.231
            advertise: 10.10.10.231
          #  port: 2152
        subnet:
          - addr: 10.45.0.1/16
            dev: ogstun
            dnn: {{ .Values.dnn }}
