apiVersion: v1
kind: Service
metadata:
  name: upf-open5gs{{ .Values.upf.config }}
  labels:
    epc-mode: upf{{ .Values.upf.config }}
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.upf.lbIP }}"
  selector:
    epc-mode: upf{{ .Values.upf.config }}
  externalTrafficPolicy: Local
  ports:
    - name: n4
      protocol: UDP
      port: 8805
      targetPort: 8805
    - name: gtpu
      protocol: UDP
      port: 2152
      targetPort: 2152
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: upf-open5gs{{ .Values.upf.config }}
#   labels:
#     epc-mode: upf
# spec:
#   selector:
#     epc-mode: upf
#   ports:
#     - protocol: UDP
#       port: 8805
#       targetPort: 8805
      
# ---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-upf-deployment{{ .Values.upf.config }}
  labels:
    epc-mode: upf{{ .Values.upf.config }}
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: upf{{ .Values.upf.config }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
      labels:
        epc-mode: upf{{ .Values.upf.config }}
    spec:   
      containers:
        - name: upf{{ .Values.upf.config }}
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
          - ip tuntap add name {{ .Values.upf.device }} mode tun;
            ip addr add 10.{{ .Values.upf.tun }}.0.1/16 dev {{ .Values.upf.device }};
            sysctl -w net.ipv6.conf.all.disable_ipv6=1;
            ip link set {{ .Values.upf.device }} up;
            sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward";
            sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf;
            iptables -t nat -A POSTROUTING -s 10.{{ .Values.upf.tun }}.0.0/16 ! -o {{ .Values.upf.device }} -j MASQUERADE;
            open5gs-upfd -c /open5gs/config-map/upf.yaml;
          volumeMounts:
          - name: open5gs-upf-config{{ .Values.upf.config }}
            mountPath: /open5gs/config-map/upf.yaml
            subPath: "upf.yaml"
          - mountPath: /dev/net/tun
            name: dev-net-tun            
      volumes:
        - name: open5gs-upf-config{{ .Values.upf.config }}
          configMap:
            name: open5gs-upf-config{{ .Values.upf.config }}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
