open5gs:
  image:
    repository: harbor.patras5g.eu/patras5g/open5gs-nam
    pullPolicy: IfNotPresent
    tag: "2.4.8.3"

webui:
  image:
    repository: harbor.patras5g.eu/patras5g/web-gui
    pullPolicy: IfNotPresent
    tag: "2.4.8.3"
  ingress:
    enabled: false
    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        tls: false

amf:
  mcc: "001"
  mnc: "01"
  tac: "100"
 
k8s:
 interface: eth0

mongo:
  image: harbor.patras5g.eu/patras5g/nextepc-mongodb
  path: /tmp/data-o5gs
  URL: "https://raw.githubusercontent.com/NAMGroup/open5gsK8s/master/subscribers.json"
