open5gs:
  image:
    repository: patras5g.eu:39080/development/open5gs-nam
    pullPolicy: IfNotPresent
    tag: "v2.3.4"

webui:
  image:
    repository: patras5g.eu:39080/development/open5gs-webui-nam-new
    pullPolicy: IfNotPresent
    tag: "v2.3.4"
  ingress:
    enabled: false
    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        tls: false

dnn: 
  upf1: "internet"
  upf2: "ims" 

amf:
  mcc: "001"
  mnc: "01"
  tac: "100"
  lbIP: "10.10.10.231"

k8s:
 interface: eth0

mongo:
  image: patras5g.eu:39080/development/nextepc-mongodb
  path: /tmp/data-o5gs
  URL: "https://raw.githubusercontent.com/NAMGroup/open5gsK8s/master/subscribers.json"

smfConfFile: "files/twoSmfConf.yaml"
