apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    parameter:
        no_ipv6: true

    smf:
        sbi:     
        - addr: 0.0.0.0
          advertise: open5gs-smf
        pfcp:
          dev: {{ .Values.k8s.interface }}
        gtpc:
          dev: {{ .Values.k8s.interface }}
        gtpu:
          dev: {{ .Values.k8s.interface }}
          #port: 2152    
        subnet:
         - addr: 10.45.0.1/16
           dnn: {{ .Values.dnn }}
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400

    nrf:
     sbi:
      name: open5gs-nrf 

    upf:
      pfcp:
<<<<<<< HEAD
        - name: upf-open5gs1
          dnn: {{ .Values.dnn }}
=======
        - name: upf-open5gs
          dnn: {{ .Values.dnn }}
>>>>>>> 4e135baa224654db25d3218def15765377671fae
