open5gs:
  image:
    repository: patras5g.eu:39080/patras5g/open5gs-nam
    pullPolicy: IfNotPresent
    tag: "2.4.8.2"

k8s:
 interface: eth0

upf:
  #config: ""
  #lbIP: "10.10.10.222"
  #tun: "45"
  device: "ogstun"
  #dnn: internet
